### ISSUE TITLE
Do I need Exchange/Office365 to run this sample?

### ISSUE THREAD

**Issue by zemien** [microsoftgraph/aspnetcore-apponlytoken-webhooks-sample#2]
I'm teaching myself how to use ASP .Net Core + Azure AD login + MS Graph API call, so I set up my experimental tenant for a personal domain (www.coderfrontline.com). I managed to Grant admin consent, but I get the following error when I try to Create subscription:

> Operation: Create; Exception: [Status Code: Unauthorized; Reason: Unauthorized] Request ID: 3821e2ce-5198-4bf9-9d15-b9811e272c87 Date: 07/02/2017 04:04:31

I double-checked that Mail.Read app permission was granted. Is this because I do not actually have any mail servers, whether Exchange or Office 365, associated with my test accounts?

**Comment by jamescro** [comment]
Yes. This sample requires an O365 tenant that has Exchange running on it.
